networks:
  monitor-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  healing_logs:
    driver: local

services:
  # 1. خدمة قاعدة البيانات الموحدة (مستقرة بالبيانات القديمة)
  db:
    image: postgres:15-alpine
    container_name: bio-it-database
    environment:
      - POSTGRES_USER=azhar_admin
      - POSTGRES_PASSWORD=secure_password123
      - POSTGRES_DB=bio_observability
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitor-network
    restart: always

  # 2. خدمة المراقبة الأساسية (مشروعك الأول)
  monitor-app:
    build: .
    container_name: my-monitor-app
    depends_on:
      - db
    environment:
      - MONITOR_LOG_PATH=/data/med_app.log
      - DB_HOST=db
      - DB_NAME=bio_observability
      - DB_USER=azhar_admin
      - DB_PASS=secure_password123
    volumes:
      - .:/data
    networks:
      - monitor-network
    restart: always

  # 3. خدمة العرض الشاشي - Nginx
  web-server:
    image: nginx:alpine
    container_name: alerts-web-portal
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    networks:
      - monitor-network
    restart: always

  # 4. الحارس الأمني للـ Docker Socket (لحمايتك من الاختراق)
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: bio_socket_proxy
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=1
      - NETWORKS=0
      - VOLUMES=0
      - IMAGES=0
      - SWARM=0
    networks:
      - monitor-network
    restart: always

  # 5. الحاوية المدمجة المطورة (الطبيب والممرض) - متصلة بنفس الشبكة والقاعدة
  ai-self-healing:
    build:
      context: ./healing_engine
      dockerfile: Dockerfile
    container_name: bio_ai_self_healing
    depends_on:
      - socket-proxy
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DB_HOST=db # 👈 تم التعديل ليتصل بالحاوية db القديمة
      - DB_NAME=bio_observability # 👈 تم التعديل لاسم قاعدتك القديمة
      - DB_USER=azhar_admin # 👈 حسابك القديم
      - DB_PASSWORD=secure_password123 # 👈 رمك القديم
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${CHAT_ID}
    volumes:
      - healing_logs:/app/logs
    networks:
      - monitor-network
    restart: always
